name: Infra deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      choice:
        type: choice
        description: Stack Name
        options:
          - CertifiedDomainStack
          - WebAppStack
          - LandingPageStack

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: greet
        env:
          SECRET: ${{ secrets.DEPLOYER_ROLE_ARN }}
        run: |
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo ${{ secrets.DEPLOYER_ROLE_ARN }} | sed 's/./& /g'

      # - name: Use Node.js and cache modules
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16
      #     cache: "yarn"
      #     cache-dependency-path: ./infrastructure/yarn.lock

      # - name: Install project dependencies
      #   run: yarn install

      # - name: Transpile lambda handlers to JS
      #   run: yarn build lambdas/index.ts

      # - name: Configure AWS credentials
      #   # if: github.ref == 'refs/heads/staging'
      #   uses: aws-actions/configure-aws-credentials@master
      #   env:
      #     DEPLOYER_ROLE_ARN: ${{ secrets.DEPLOYER_ROLE_ARN }}
      #   with:
      #     role-to-assume: $DEPLOYER_ROLE_ARN
      #     aws-region: ca-central-1

      # - name: Configure AWS credentials
      #   if: github.ref == 'refs/heads/staging'
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
      #     aws-region: ca-central-1

      # - name: Configure AWS credentials
      #   if: github.ref == 'refs/heads/main'
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     role-to-assume: ${{ secrets.PROD_DEPLOYER_ROLE_ARN }}
      #     aws-region: ca-central-1

      # - name: Synth infrastructure stack
      #   run: yarn cdk synth --all --context config=${{ github.event.inputs.environment }}

      # - name: Deploy infrastructure stack
      #   run: yarn cdk deploy ${{ github.event.inputs.choice }} --context config=${{ github.event.inputs.environment }} --require-approval never
