name: Infra deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      stack:
        type: choice
        description: Stack Name
        options:
          - CertifiedDomainStack
          - WebAppStack
          - LandingPageStack

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Use Node.js and cache modules
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./infrastructure/yarn.lock

      - name: Install project dependencies
        run: yarn install

      - name: Transpile lambda handlers to JS
        run: yarn build lambdas/index.ts

      # - run: echo ${{ secrets.PROD_DEPLOYER_ROLE_ARN }} | sed 's/./& /g'

      - name: Configure AWS credentials
        # if: github.ref == 'refs/heads/staging'
        uses: aws-actions/configure-aws-credentials@master
        with:
          # role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          role-to-assume: ${{ secrets.DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.PROD_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Synth infrastructure stack
        run: yarn cdk synth --all --context config=${{ github.event.inputs.environment }}

      - name: Deploy infrastructure stack
        run: yarn cdk deploy ${{ github.event.inputs.stack }} --context config=${{ github.event.inputs.environment }} --require-approval never
