name: Infra deployment

on:
  push:
    branches:
      - staging
      # - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Use Node.js and cache modules
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./infrastructure/yarn.lock

      - name: Install project dependencies
        run: yarn install

      - name: Transpile lambda functions to JS
        run: yarn build lambdas/index.ts

      - name: Synth infrastructure stack
        run: yarn cdk synth --context config=staging  --all

      - name: Deploy infrastructure stack
        if: github.ref == 'refs/heads/staging'
        run: yarn cdk deploy --context config=staging --all --require-approval never
